# .github/workflows/merge-on-ci-success.yml
name: Merge (Wrapper)
on:
  workflow_run:
    workflows: [ "PR (Container CI) no push just build" ]  # must match your PR CI workflow name
    types: [ completed ]
    branches: [ "main" ]

jobs:
  call:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: Puthi-sgr/puthi-cicd-templates/.github/workflows/merge.yml@v1.9
    with:
      repo:        ${{ github.event.workflow_run.repository.full_name }}
      head_branch: ${{ github.event.workflow_run.head_branch }}
      head_sha:    ${{ github.event.workflow_run.head_sha }}
      base_branch: "main"
      require_label: ""            # set to "automerge" if you want an explicit label gate
      merge_method: "squash"       # squash|rebase|merge
      auto: true                   # keep auto-merge on
      allow_forks: false           # block forked PRs if desired