name: Main (Container Build & Push)
on: { push: { branches: ["main"] } }

jobs:
  ci:
    uses: Puthi-sgr/puthi-cicd-templates/.github/workflows/container-ci.yml@v1.2
    with:
      image_name: ghcr.io/puthi-sgr/docker-laravel
      stack: php-laravel
      build_mode: full
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}