name: PR (Container CI) no push just build
on: { pull_request: { branches: ["main"] } }

jobs:
  ci:
    uses: Puthi-sgr/puthi-cicd-templates/.github/workflows/container-ci.yml@v1.2
    with:
      image_name: ghcr.io/puthi-sgr/docker-laravel #image path 
      stack: php-laravel
      build_mode: full
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
